### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gregoirefra** [WalkingMachine/sara_ui#1]
- [ ] Log window de different topic
- [ ] Status des node
- [ ] Etat des ordi (ip, power, etc...) 
- [ ] Moyen d'écrire sur un topic choisi
- [ ] Call de service ROS
