### ISSUE TITLE
Todo - Monitoring

### ISSUE THREAD

**Issue by lucasmaurice** [WalkingMachine/sara_ui#3]
**- Laptop :**
- [x] CPU Usage
- [x] CPU Temperature
- [ ] GPU Usage
- [ ] GPU Temperature
- [x] Memory Usage
- [x] Memory Size
- [ ] Memory Temperature
- [ ] Disk Space
- [ ] Disk Size
- [ ] Disk Temperature
- [x] Laptop Battery State

**- Network :**
- [ ] Laptop IP Adresses
- [ ] Nodes IP Adresses
- [ ] Select roscore ip adress

**- Statistics :**
- [ ] Usage Time
- [ ] Time Before Shutdown

**- Sensors :**
- [ ] Battery Voltage
- [ ] Battery Charge Rate
- [ ] Current (live)
- [ ] Current (peak)

**- Motors :**
- [ ] Temperature

**Comment by lucasmaurice** [comment]
For GPU usage :
``` shell
nvidia-smi --query-gpu=utilization.gpu,utilization.memory,temperature.gpu --format=csv
```
Returning GPU and GPU memory usage and GPU temperature.

More informations here : [NVIDIA Doc](http://nvidia.custhelp.com/app/answers/detail/a_id/3751/~/useful-nvidia-smi-queries)

**Comment by lucasmaurice** [comment]
For HDD Usage : 
``` shell
df /
```

**Comment by lucasmaurice** [comment]
For Battery Usage, show here :
```shell 
/sys/class/power_supply/BAT0/
```
